/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:526790dd-3ab1-4420-acf2-c9fca567e90f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Tj4PnIwdv",
    "aws_user_pools_web_client_id": "2tm0fd900ush7477g39c2dmkq1",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://exrwhfzwmzg4pbwjq6shaxkgxy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ju5j5iwjavdf7c2vw4zz7dpzse"
};


export default awsmobile;
